### ISSUE TITLE
Isuues About Reproduction

### ISSUE THREAD

**Issue by 1999swallowthemoon** [TangTao-PKU/ARTS#1]
Thank you for your great work! I have the following questions:

1. While training the full network for final mesh prediction, I executed the command python ./main/train.py --cfg ./config/train_mesh_h36m.yml --gpu 1, but I encountered the following error: pred, target = pred * target_valid, target * target_valid RuntimeError: The size of tensor a (16) must match the size of tensor b (32) at non-singleton dimension 1. Upon investigation, I found that this error occurs during the computation of loss5, where the shapes of evo_pose (32,16,17,3) and gt_lift3dpose and val_lift3dpose (32,17,3) do not match. The former includes the entire sequence, while the latter only includes the coordinates of the middle frame. I hypothesized that loss5 and loss6 serve similar purposes, so I removed loss5 to allow the program to run. However, I observed that the MPJPE and MPVPE remained at approximately 187 and 220, respectively, and subsequent training resulted in NaN values. I am concerned whether the removal of loss5 is the cause of these issues. Could this be the reason for the high errors?

2. I noticed that, according to the description in your paper, motion-centric features F' are utilized to refine the initial SMPL pose and shape parameters. However, in the code, it appears that these motion-centric features F' are directly used to predict the SMPL pose and shape parameters. Is my understanding incorrect regarding this discrepancy between the implementation and the description in the paper?

3. Additionally, in the TIK module, it is mentioned that h36m_jregressor = np.load('./J_regressor_h36m.npy'), but no specific file is provided or indicated. Consequently, I used a commonly available J_regressor_h36m.npy file from previous work. I am unsure whether this could be contributing to the high errors.

Looking forward to and thank you for your answer!

**Comment by TangTao-PKU** [comment]
Thank you for your interest in our work! Due to the double-blind review process during submission, we have removed some code containing personal information, which may cause issues in data processing and performance when running it directly. As I am currently quite busy, I expect to organize and update the **latest code along with the our checkpoints** either when the MM paper is published or after the CVPR submission. Thank you again for your attention!

**Comment by TangTao-PKU** [comment]
Thank you for your interest in our work !

1.Our earliest version was a de-anonymized code release, which included some redactions of personal information. After the MM conference, we uploaded the latest version of the code to ensure it could run and reproduce the performance reported in Table 1.
2.The fused motion-centric features are fed into the SMPL regressor. Within the regressor, the SMPL parameters are first regressed from the motion-centric features, and then residuals are applied to the input init_pose and init_shape.
3.The usage of J_regressor_h36m.npy from previous works has no impact. We will update the README later to include the link for this file.
